---
- name: Copy private key to admin node
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/id_ssh_rsa"
    dest: "/home/{{ owner }}/.ssh/"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "0400"
    remote_src: false
