---

- name: Setup template
  ansible.builtin.template:
    src: Vagrantfile.j2
    dest: "{{ project_directory }}/Vagrantfile"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: staff
    mode: "0644"
