---
- name: Copy public key to webservers node
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/id_ssh_rsa.pub"
    dest: "/home/{{ owner }}/.ssh/"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "0644"
    remote_src: false
- name: Add public key to authorized key list
  ansible.posix.authorized_key:
    user: "{{ owner }}"
    state: present
    key: "{{ lookup('file', '{{ tmp_dir }}/id_ssh_rsa.pub') }}"
